custom_user_field_ID:
  default: 0
  type: integer
custom_favorite_filters_allowed_groups:
  type: list
  list_type: group
  default: "10" #trust_level_0
  disallowed_groups: "0|4" #everyone, anonymous_users
  resolve_group_membership: true
show_for_admin:
  default: true
  type: bool
default_favorites:
  default: ""
  type: string
default_favorite_filters_groups:
  type: list
  list_type: group
  default: "4|5" #anonymous_users, logged_in_users
  resolve_group_membership: true
